## Configuration file for the SNPpop pipeline
# Het-v paper
# ---------------------------------------------------

# List of samples to analyze
SampleIDs: ["PaWa1p", "PaWa2m", "PaWa3p", "PaWa4p", "PaWa7m", "PaWa8p", "PaWa9m", "PaWa10p", "PaWa11m", "PaWa12p", "PaWa13m", "PaWa14p", "PaWa15m", "PaWa16p", "PaWa17m", "PaWa18p", "PaWa19m", "PaWa21m", "PaWa22m", "PaWa23p", "PaWa24m", "PaWa25p", "PaWa26m", "PaWa27p", "PaWa28m", "PaWa29p", "PaWa32p", "PaWa33m", "PaWa36p", "PaWa37m", "PaWa38p", "PaWa39m", "PaWa40m", "PaWa41p", "PaWa42m", "PaWa43p", "PaWa44m", "PaWa45p", "PaWa46p", "PaWa47m", "PaWa49m", "PaWa52p", "PaWa53m", "PaWa54m", "PaWa55p", "PaWa56m", "PaWa57p", "PaWa58m", "PaWa59m", "PaWa60p", "PaWa61m", "PaWa62p", "PaWa63p", "PaWa64m", "PaWa66m", "PaWa67p", "PaWa68m", "PaWa69p", "PaWa70m", "PaWa71p", "PaWa72m", "PaWa76p", "PaWa77m", "PaWa78p", "PaWa79m", "PaWa81p", "PaWa83m", "PaWa85p", "PaWa86m", "PaWa87p", "PaWa88p", "PaWa89p", "PaWa91p", "PaWa92p", "PaWa94p", "PaWa95p", "PaWa96m", "PaWa97p", "PaWa98m", "PaWa99p", "PaWa100p", "PaWa101m", "PaWa102p", "PaWa103m", "PaWa104m", "PaWa105p", "PaWa106p", "PaWa107m", "PaWa108m", "PaWa109p", "PaWa115m", "PaWa116p", "PaWa117m", "PaWa118p", "PaWa122m", "PaWa123p", "PaWa124p", "PaWa125m", "PaWa126p", "PaWa127m", "PaWa128p", "PaWa129p", "PaWa137m", "PaWa138m", "PaWa142p", "PaWa143m", "CBS433.50p", "CBS455.64m", "PaTgp", "PaYp", "PaZp", "PaSp"]

# Path to Illumina samples
Illumina: "data/Illumina" # Expecting files like "data/Illumina/{sample}_postQC.1.fq.gz" and "data/Illumina/{sample}_postQC.2.fq.gz"

# The reference genome
Podan2file: "data/Podan2/Podan2_AssemblyScaffoldsmt.fa" # Exactly like this, available at https://github.com/johannessonlab/SpokPaper/tree/master/Fig4_S3_Backcrosses/extras

# Path to repeated elements library
TElib: "/some/path/to/FungiRepbaseEspagneGioti.lib" # Available at https://github.com/johannessonlab/SpokPaper/tree/master/Fig4_S3_Backcrosses/extras

# Plotting script
rscript: "scripts/PCASNPpop_SNPRelate.R"

# Metadata file
metadata: "data/SNPpopMetadata.csv"

# Mating file
matingdata: "data/PodosporaMating.csv"
