# Samples NOT in Wageningen (to be removed)
notWa: ["PaSp", "PaZp", "PaYp", "CBS433.50p", "CBS455.64m", "PaTgp"]

# Samples divided in mating groups
groupV: ["PaWa1p", "PaWa2m", "PaWa3m", "PaWa4p", "PaWa10p", "PaWa11m", "PaWa12p", "PaWa13m", "PaWa14p", "PaWa16p", "PaWa19m", "PaWa22m", "PaWa23p", "PaWa24m", "PaWa29p", "PaWa32p", "PaWa33m", "PaWa36p", "PaWa37m", "PaWa39m", "PaWa40m", "PaWa41p", "PaWa42m", "PaWa43p", "PaWa44m", "PaWa52p", "PaWa53m", "PaWa54m", "PaWa55p", "PaWa56m", "PaWa58m", "PaWa59m", "PaWa62p", "PaWa66m", "PaWa67p", "PaWa68m", "PaWa69p", "PaWa70m", "PaWa81p", "PaWa83m", "PaWa100p", "PaWa85p", "PaWa87p", "PaWa92p", "PaWa94p", "PaWa95p", "PaWa98m", "PaWa99p", "PaWa102p", "PaWa106p", "PaWa117m", "PaWa122m", "PaWa123p", "PaWa125m", "PaWa127m", "PaWa129p", "PaWa138m"]
groupA: ["PaWa7m", "PaWa8p", "PaWa9m", "PaWa15m", "PaWa17m", "PaWa18p", "PaWa21m", "PaWa25p", "PaWa26m", "PaWa27m", "PaWa28m", "PaWa38p", "PaWa45p", "PaWa46p", "PaWa47m", "PaWa49m", "PaWa57p", "PaWa60p", "PaWa61m", "PaWa63p", "PaWa64m", "PaWa71p", "PaWa72m", "PaWa76p", "PaWa77m", "PaWa78p", "PaWa79m", "PaWa86m", "PaWa88p", "PaWa89p", "PaWa91p", "PaWa96m", "PaWa97p", "PaWa101m", "PaWa103m", "PaWa104m", "PaWa105p", "PaWa107m", "PaWa108m", "PaWa109p", "PaWa115m", "PaWa116p", "PaWa118p", "PaWa124p", "PaWa126p", "PaWa128p", "PaWa137m", "PaWa142p", "PaWa143m"]

# The variants file
vcf: "SNPpop/results/PodoPop-snps-NoTEs-gatkPASS-NoSibs-miss1.vcf.gz"

# Number of chromosomes (assuming vcf has contigs names like "chromosome_1")
NCHR: 7

# Number of randomly sampled windows from each chromosome
NWIN: 30

# Length of LD windows for decay
WINLEN: 50000

# Thining of the SNPs for the intra and interchromosomal LD calculation
THIN: 1000

# Thining for het-v and het-r areas
THINhet: 1000

# MAF for LD heatmaps
MAF: 0.02
MAFhet: 0.02

# Define the het-v and het-r areas
hetvSTART: 725000
hetvEND: 1725000

hetrSTART: 2250000
hetrEND: 3250000

# Manipulate vcf files
vcfconcat4LD: "scripts/vcfconcat4LD.py"

# Plotting scripts
PaLDPlot: "scripts/PaLDPlot-nls-grs.R"
PaLDheatmap: "scripts/PaLDheatmap.R"
